-- CreateTable
CREATE TABLE "Pilot" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "PILOTO" TEXT NOT NULL,
    "TELEFONO" TEXT,
    "DNI" TEXT,
    "FECHA_NAC" TEXT,
    "LICENCIA" TEXT,
    "CMA" TEXT,
    "AW109" TEXT,
    "BO105" TEXT,
    "CONTROL_BIENAL" TEXT,
    "INSP_RECONOC" TEXT,
    "SIMULADOR" TEXT,
    "CTRL_IDONEIDAD" TEXT,
    "CTRL_RUTA" TEXT,
    "CTRL_VLO_INST" TEXT,
    "EXP_RECIENTE" TEXT,
    "ULT_FOLIADO" TEXT,
    "CRM_FFHH" TEXT,
    "MERC_PELIGROSAS" TEXT,
    "INTERF_ILICITA" TEXT,
    "MOE" TEXT,
    "SMS" TEXT,
    "CURSO_AERONAVE" TEXT,
    "VACACIONES" TEXT,
    "INSP_IR" TEXT,
    "BASE" TEXT,
    "HUET" TEXT,
    "RO" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Pilot_DNI_key" ON "Pilot"("DNI");
